# Generated by Django 4.0.3 on 2022-03-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
        migrations.AddField(
            model_name='collection',
            name='text',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Input',
        ),
    ]
