# Generated by Django 4.0.3 on 2022-03-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_collection_name_collection_text_delete_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='txtfile',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
