# Generated by Django 4.0.3 on 2022-03-28 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_collection_txtfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='txtfile',
        ),
    ]
